### ISSUE TITLE
Was the onAnimationEnd handler removed intentionally, or is that an oversight on 2.x?

### ISSUE THREAD

**Issue by invig** [octopitus/rn-sliding-up-panel#107]
### Issue Description

Question: 

It looks like the onAnimationEnd handler was removed when moving from transitionTo() to show(), was that an intentional decision / if we were to do a PR to re-add a hook for knowing when the transition finishes would that be accepted?

---
### Environment
* Version: 2.x

**Comment by octopitus** [comment]
No worries. I'm adding it back since many people depend on it to implement their own drag snapping. You can try out on branch momentum-events (`yarn add https://github.com/octopitus/rn-sliding-up-panel.git#momentum-events`).

You must use `triggerAnimation` method if you want to know when the animation finishes, `show()` and `hide()` won't have. Example:

```js
this._panel.triggerAnimation({
  toValue: 360,
  onAnimationEnd: (value) => console.log(value) // `value` is the position of the panel where it stops
})
```

There are `onMomentumDragStart` and `onMomentumDragEnd` adding along with that but will need more time. I haven't created PR yet.
