### ISSUE TITLE
panel.show() and panel.hide() don't slide to proper position.

### ISSUE THREAD

**Issue by epurban** [octopitus/rn-sliding-up-panel#109]
### Issue Description

I am trying to create a snapping mechanism, which when you let go of the panel while dragging, it will snap to either the very top, or a bottom point. I'm using onDragEnd to call a function which checks the gestureState and determines where to send it, then I call panel.show(TOP) or panel.hide() to send it to the bottom point. However, it rarely takes my panel to the intended targets!

```javascript
draggableRange: {
        top: height,
        topBreak: height * 0.95,
        midBreak: height * 0.40,
        bottomBreak: 200,
        bottom: 170,
}
```

```javascript
dragEnd(position, gestureState) {
    // If panel was moving upwards, do upwards operations
    if (gestureState.vy < 0) {
      // If user moves the panel above middleUp, drag it to the top
      if (position >= this.state.draggableRange.bottomBreak) {
        this._panel.show(this.state.draggableRange.top);
        this.onSwipeToTop();
      } else {
        // Else, hide it
        this._panel.hide()
      }
    } else {
      // If panel was moving downwards, do downward operations
      if (position >= this.state.draggableRange.topBreak) {
        this._panel.show(this.state.draggableRange.top)
      } else {
        // Else, hide it
        this._panel.hide()
      }
    }
  }
```

###  GIF of issue
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/22136514/55678791-9c941080-58cd-11e9-9706-a1d10ad59458.gif)

---
### Environment
* Version: 2.1.0
* React Native version: 0.57
* Platform(s) (iOS, Android, or both?): iOS 12.2
* Device info: iPhone SE, Expo 32, Release mode

**Comment by Eralyne** [comment]
How do you calculate screen height for your  height variable?

Also, do you have allowMomentum={false} on your SlidingUpPanel?

I, personally, don't see anything other than those two things that could be causing this problem. The slide up and hide appear to be fine.

**Comment by epurban** [comment]
I have allowMomentum={false} on yes. Should it not be? I am calculating height as 

`const {height} = Dimensions.get('screen');`

**Comment by Eralyne** [comment]
Yeah, keep it at momentum false.

I've never seen get('screen') for the Dimensions. Can you use Dimensions.get('window') instead? 

Also, in your gif it seems that your hiding the status bar when the panel moves up? I'm pretty sure that will cause your height to be a bit messed up because with it hidden the top should be bigger but, if you don't update your height on re-render, your height value will stay the same while the actual height changes.

**Comment by Eralyne** [comment]
Also, if the things I provided do not fix the issue then I greatly suggest putting some debug prints for position and just messages in the dragEnd if statements to make sure that the show top is actually firing and find the problem through that. I wish I could help more at this time but it's pretty late right now.

**Comment by octopitus** [comment]
This is true due to the fact that the deceleration technique using an exponential decay concept similar to [Animated.decay](https://facebook.github.io/react-native/docs/animated#decay). It starts with an initial velocity and gradually slows to a stop. The `toValue` passing to `show()` method is actually to calculate this initial velocity.

**Comment by octopitus** [comment]
Should be fixed on latest version. But if it still happens to you. Feel free to let me know.
