### ISSUE TITLE
currentlyFocusedInput deprecated

### ISSUE THREAD

**Issue by Dellybro** [octopitus/rn-sliding-up-panel#184]
### Issue Description

Line 315 of slidingUpPanel.js needs to be edited 

```
const node = TextInput.State.currentlyFocusedField()
```
should be
```
const node = TextInput.State.currentlyFocusedInput()
```

**Comment by xapai** [comment]
It's not that easy to fix, as my experience shows. Changing to `currentlyFocusedInput` results in that kind of error:

![image](https://user-images.githubusercontent.com/5209820/89765743-946e6580-daff-11ea-9fbc-012411b06ffb.png)

**Comment by xapai** [comment]
It happen because of this code:

```
UIManager.viewIsDescendantOf(node, findNodeHandle(this._content), (isDescendant) => {
        isDescendant && this.scrollIntoView(node)
      });
```

`viewIsDescendantOf` waits for reactTag (number) which is a reference to a react fiber element. But, `currentlyFocusedInput` returning object, and that break things.

![image](https://user-images.githubusercontent.com/5209820/89771472-08613b80-db09-11ea-838a-b7319774a324.png)

**Comment by xapai** [comment]
You can track progress on this issue on this PR:

https://github.com/octopitus/rn-sliding-up-panel/pull/185

**Comment by octopitus** [comment]
Fixed in v2.4.4

**Comment by mwerder** [comment]
when do you release v2.4.4? latest on npm is still 2.4.3

**Comment by octopitus** [comment]
@mwerder Sorry forgot to publish new verison. Should have been updated.
