### ISSUE TITLE
Performance on open and close

### ISSUE THREAD

**Issue by barnir** [octopitus/rn-sliding-up-panel#50]
Hey, i'm using this panel just with a press to open and press to close (change visible to true and false).
My issue is with the animation.. on doing so.. it feels sluggish.. makes it look line it has really performance issues.. was expecting it to be smoother
Any tip to solve this? or even disable the animation.. 

`  <SlidingUpPanel
          visible={this.state.isPanelVisible}
          showBackdrop={false}
          height={height + 160}
          allowDragging={false}>`

Does the content inside the panel affect this?

**Comment by octopitus** [comment]
Yes, the content inside effects the performance of the panel. If your content changes frequently based on some extra conditions, likely you need to use `shouldComponentUpdate` to prevent it from unnecessary re-rendering.

**Comment by VenomApps** [comment]
Why is there no useNativeDriver?

**Comment by octopitus** [comment]
@VenomApps This package using PanResponder as the gesture handler. Unfortunately, [PanResponder does not support `useNativeDriver: true`](https://github.com/facebook/react-native/issues/13377).

**Comment by VenomApps** [comment]
Performance suffers greatly because of it. It’s a huge set back for the project not being able to off load as much work as possible to the native thread. There should be an option to useNativeDriver if pan reaponder turned off or something along those lines to try to improve the performed especially during heavy js operations. I have not tried it in production mode but solely based off dev it is quite bad. Lags often and stutters when opening.
